config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


post '/application/finder' => 'application#finder', as: 'finder'


root "application#index"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
	def self.canonica(word)
   		 word.split("").sort.join
 	end

  	def self.search_canonical(user_word)
   		 word_canonical = self.canonica(user_word)
    	word = Word.where(canonical: word_canonical)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

require 'net/http'

  
  def index
 
	url = 'http://setgetgo.com/randomword/get.php'
	uri = URI(url)
	@response = Net::HTTP.get(uri)

  end

  def finder
  
   params[:anagram]

  end







end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<h1> <%= @response %> </h1>


<%= form_for :anagram, url: finder_path do |form| %>
  <%= form.text_field :anagram %>
  <%= form.submit  %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anagrams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>